import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
=======
import { Poppins } from "next/font/google";
>>>>>>> 0fda8690dab4afbaa8eb2b62c309f872ad96f71f
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
=======
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Optional: you can customize
});

export const metadata: Metadata = {
  title: "Dhagay Shagay",
>>>>>>> 0fda8690dab4afbaa8eb2b62c309f872ad96f71f
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<style>
@import url('https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
</style>
=======
        className={`bg-white antialiased ${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}
      >
>>>>>>> 0fda8690dab4afbaa8eb2b62c309f872ad96f71f
        {children}
      </body>
    </html>
  );
}
